# Generated by Django 5.1.2 on 2024-10-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_room_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='base_price',
        ),
        migrations.AddField(
            model_name='room',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
